# Generated by Django 5.2.9 on 2025-12-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posts/')),
                ('is_practice', models.BooleanField(default=False, verbose_name='模写（練習用）')),
                ('tag', models.CharField(choices=[('hand', '手の練習'), ('face', '顔・表情'), ('pose', '全身・ポーズ'), ('copy', '完全模写'), ('other', 'その他')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
